env: "local"
port: 5000
secret: "egorlox"
static: "./static"
storage:
  host: "localhost"
  port: 5444
  user: "postgres"
  password: "1234"
  dbname: "pets"
telegram:
  token: "" # TODO: вынести в env
