env: "local"
port: 5000
secret: "egorlox"
static: "./static"
storage:
  host: "localhost"
  port: 5444
  user: "postgres"
  password: "1234"
  dbname: "pets"
telegram:
  token: ""
clients:
  sso:
    address: "127.0.0.1:44044"
    timeout: "10s"
    retriesCount: 3